apiVersion: v1
baseDomain: clearwater.devops.gov.bc.ca
controlPlane: 
  hyperthreading: Enabled   
  name: master
  platform:
    azure:
      osDisk:
        diskSizeGB: 150
      type: Standard_D8s_v3
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    azure:
      type: Standard_D2s_v3
      osDisk:
        diskSizeGB: 150 
      zones: 
      - "1"
      - "2"
      - "3"
  replicas: 3
metadata:
  name: ocp4lab
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    region: canadacentral 
    baseDomainResourceGroupName: ocp4lab
pullSecret: '{"auths": ...}' 
sshKey: ssh-ed25519 AAAA... 