apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    release.openshift.io/create-only: 'true'
  name: cluster
spec:
  identityProviders:
    - github:
        clientID: XXX
        clientSecret:
          name: github-oauth
        hostname: ''
        organizations: []
        teams:
          - BCDevOps/azure-sandbox-user-team
      mappingMethod: claim
      name: github
      type: GitHub