apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance" 
  namespace: "openshift-logging"
spec:
  managementState: "Managed"  
  logStore:
    type: "elasticsearch"
    elasticsearch:
      resources:
        limits:
          cpu: 1
          memory: 6Gi
        requests:
          cpu: 1
          memory: 6Gi
      nodeCount: 3 
      nodeSelector: 
          node-role.kubernetes.io/infra: ''
      storage:
        storageClassName: azure-disk
        size: 200G
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"  
    kibana:
      replicas: 1
      nodeSelector: 
          node-role.kubernetes.io/infra: ''
  curation:
    type: "curator"  
    curator:
      schedule: "30 3 * * *"
      nodeSelector: 
          node-role.kubernetes.io/infra: ''
  collection:
    logs:
      type: "fluentd"  
      fluentd: {}

