---
apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: hourly-namespace-cpu-usage
  namespace: openshift-metering
spec:
  query: namespace-cpu-usage
  schedule:
    period: "hourly"
    hourly: 
      minute: 00
      second: 00
---
apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: hourly-namespace-memory-usage
  namespace: openshift-metering
spec:
  query: namespace-memory-usage
  schedule:
    period: "hourly"
    hourly: 
      minute: 00
      second: 00
---
apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: hourly-namespace-pvc-usage
  namespace: openshift-metering
spec:
  query: namespace-persistentvolumeclaim-usage
  schedule:
    period: "hourly"
    hourly: 
      minute: 00
      second: 00